name: Train Model
description: Traines a model on labled spectograms
inputs:
  - {
      name: GCS Bucket,
      type: String,
      default: "bird-song-identification",
      description: "Name of Google Cloud Storage bucket that should be used for caching spectrogram files",
    }
  - {
      name: Input Path,
      type: Directory,
      description: "Path of the data folder",
    }
  - {
      name: Chunk Length,
      type: Integer,
      description: "Chunk length in milliseconds",
    }
  - {
      name: Batch Size,
      type: Integer,
      default: 32,
      description: "Size of the training batches",
    }
  - {
      name: Number Epochs,
      type: Integer,
      default: 25,
      description: "Number of Epochs for the training/validation cycle",
    }
  - {
      name: Multi Label Classification,
      type: Bool,
      default: False,
      description: "Whether a multi-label classification model should be use",
    }
  - {
      name: Multi Label Classification Threshold,
      type: Float,
      default: 0.5,
      description: "Threshold for assigning samples to positive class in multi-label classification",
    }
outputs:
  - { name: Output Path, type: Directory }
implementation:
  container:
    image: us.gcr.io/gcp-bakdata-kubeflow-cluster/bird-song-identification:latest
    command:
      [
        python,
        kubeflow_pipeline/run_pipeline.py,
        train_model,
        --input_path,
        { inputPath: Input Path },
        --gcs_bucket,
        { inputValue: GCS Bucket },
        --chunk_length,
        { inputValue: Chunk Length },
        --batch_size,
        { inputValue: Batch Size },
        --number_epochs,
        { inputValue: Number Epochs },
        --multi_label_classification,
        { inputValue: Multi Label Classification },
        --multi_label_classification_threshold,
        { inputValue: Multi Label Classification Threshold },
        --output_path,
        { outputPath: Output Path },
      ]
